export default function Wall() {
    return(
        <>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
            <h1>Wall</h1>
        </>
    )
}